extends Control

@onready var player = $"../../"

@onready var velocNumb = $"Velocity"
@onready var horzVeloc = $"HorzVeloc"
@onready var vertVeloc = $"VertVeloc"
@onready var addedVeloc = $"AddedVeloc"
@onready var jumps = $"Jumps"
@onready var grapples = $"Grapples"

func _physics_process(delta):
	velocNumb.text = "Velocity: " + str(round(player.velocity.length()))
	horzVeloc.text = "Horizontal Velocity: " + str(round(player.velocity.x))
	vertVeloc.text = "Vertical Velocity: " + str(round(player.velocity.y))
	addedVeloc.text = "Added Velocity: " + str(round(abs(player.addedveloc)))
	jumps.text = "Jumps: " + str(player.jumps)
	if player.find_child("Grapple"):
		grapples.text  = "Grapples: " + str(player.find_child("Grapple").grapples)
func _process(delta):
	size = get_viewport().size
